import { readFileSync } from 'node:fs'
import { posix } from 'node:path'
import { composedPathOf } from './contributions.js'
import { composeAppCss } from './css.js'
import type { MaterializeResult } from './materialize.js'
import { composeMessages, type MessageOverlay } from './messages.js'
import type { FileSource, OverlayResult } from './overlay.js'
import { compareCodeUnits, normalizePackPath } from './paths.js'
import { OWNED_DIRECTORIES, type Host, type Pack } from './sources.js'
import type { UiPackManifest } from './types.js'

export const GENERATED_MARKER = '.pv-compose-generated'
const HEADER_TEXT =
  'Generated by @project-vault/composition-kit (pv-compose). DO NOT EDIT.\n' +
  'This directory is deleted and rewritten on every compose. Change the UI pack instead.\n'
const APP_CSS = 'src/app.css'
const SETTINGS = 'project.inlang/settings.json'

export interface Assembly {
  files: Map<string, FileSource>
  problems: string[]
  notes: string[]
}

function text(content: string): FileSource {
  return { kind: 'text', content: Buffer.from(content) }
}

function textOf(source: FileSource | undefined): string {
  if (source === undefined) return ''
  return source.kind === 'file' ? readFileSync(source.abs, 'utf8') : source.content.toString('utf8')
}

/** The "do not edit" header and a catch-all `.gitignore` in every generated directory. */
function headerFiles(): [string, FileSource][] {
  return OWNED_DIRECTORIES.flatMap((owned) => [
    [`${owned}/${GENERATED_MARKER}`, text(HEADER_TEXT)] as [string, FileSource],
    [`${owned}/.gitignore`, text('*\n')] as [string, FileSource],
  ])
}

/** The pack's message overlay files: `<messages dir>/<locale>.json`, directly in that directory. */
function messageOverlays(
  manifest: UiPackManifest,
  pack: Pack,
  problems: string[]
): MessageOverlay[] {
  if (manifest.messages === undefined) return []
  const dir = normalizePackPath(manifest.messages)
  if (dir === null) {
    problems.push(`messages: "${manifest.messages}" must be a directory inside the UI pack.`)
    return []
  }
  const prefix = `${dir}/`
  return [...pack.files]
    .filter(
      ([rel]) =>
        rel.startsWith(prefix) && rel.endsWith('.json') && !rel.slice(prefix.length).includes('/')
    )
    .map(([rel, abs]) => ({
      file: rel,
      locale: rel.slice(prefix.length, -'.json'.length),
      text: readFileSync(abs, 'utf8'),
    }))
    .sort((a, b) => compareCodeUnits(a.file, b.file))
}

function hostCatalogues(host: Host): Map<string, string> {
  return new Map(
    [...host.files]
      .filter(([rel]) => rel.startsWith('messages/') && rel.endsWith('.json'))
      .map(([rel, abs]) => [
        rel.slice('messages/'.length, -'.json'.length),
        readFileSync(abs, 'utf8'),
      ])
  )
}

/** Writes the theme `@import`, the CM `@source` and the vendored shared `@source` into app.css. */
function applyCss(
  files: Map<string, FileSource>,
  manifest: UiPackManifest,
  mat: MaterializeResult,
  out: Assembly
): void {
  const themeDest = composedPathOf(manifest.theme, mat)
  const css = composeAppCss(textOf(files.get(APP_CSS)), {
    cmCode: mat.relocated.length > 0,
    ...(themeDest === null ? {} : { themeImport: `./${posix.relative('src', themeDest)}` }),
  })
  out.problems.push(...css.problems)
  out.notes.push(...css.notes)
  if (css.problems.length === 0) files.set(APP_CSS, text(css.css))
}

/** The complete composed file set: the overlaid host tree, the materialized CM code, the rewritten
 * overlay files, app.css with the theme, the message overlays, and the generated-directory headers. */
export function assemble(
  manifest: UiPackManifest,
  host: Host,
  pack: Pack,
  overlay: OverlayResult,
  mat: MaterializeResult
): Assembly {
  const out: Assembly = { files: new Map(overlay.files), problems: [], notes: [] }
  for (const [dest, content] of [...mat.files, ...mat.overlayEdits]) {
    out.files.set(dest, { kind: 'text', content })
  }
  applyCss(out.files, manifest, mat, out)
  const messages = composeMessages({
    host: hostCatalogues(host),
    settings: textOf(out.files.get(SETTINGS)),
    overlays: messageOverlays(manifest, pack, out.problems),
  })
  out.problems.push(...messages.problems)
  out.notes.push(...messages.notes)
  for (const [dest, content] of messages.files) out.files.set(dest, text(content))
  for (const [dest, source] of headerFiles()) out.files.set(dest, source)
  return out
}
