import { existsSync } from 'node:fs'
import { isAbsolute, join, relative, resolve } from 'node:path'
import { GENERATED_MARKER } from './assemble.js'
import { OWNED_DIRECTORIES } from './sources.js'

function isInside(parent: string, child: string): boolean {
  const path = relative(parent, child)
  return path === '' || (!path.startsWith('..') && !isAbsolute(path))
}

function isStrictlyInside(parent: string, child: string): boolean {
  return resolve(parent) !== resolve(child) && isInside(parent, child)
}

/** An output that overlaps an input corrupts both: refuse before anything is read or deleted. */
export function overlapProblems(appRoot: string, packRoot: string, hostDir: string): string[] {
  const problems: string[] = []
  if (resolve(appRoot) === resolve(packRoot)) {
    problems.push(
      `The app root and the UI pack root are the same directory (${appRoot}); the output would overwrite the input.`
    )
  }
  for (const [label, dir] of [
    ['web-host', hostDir],
    ['the UI pack', packRoot],
  ] as const) {
    for (const owned of OWNED_DIRECTORIES) {
      if (isInside(join(resolve(appRoot), owned), resolve(dir))) {
        problems.push(
          `${label} (${dir}) is inside the generated directory ${join(appRoot, owned)}, which the composer deletes.`
        )
      }
    }
    if (isStrictlyInside(dir, appRoot)) {
      problems.push(
        `The app root (${appRoot}) is inside ${label} (${dir}); the output would overlap the input.`
      )
    }
  }
  return problems
}

/** A generated directory with content but no header was not made by pv-compose: never wipe it. */
export function ownershipProblems(appRoot: string): string[] {
  return OWNED_DIRECTORIES.flatMap((owned) => {
    const dir = join(appRoot, owned)
    return existsSync(dir) && !existsSync(join(dir, GENERATED_MARKER))
      ? [
          `Refusing to replace ${dir}: it has no ${GENERATED_MARKER} header, so it was not generated by pv-compose (a hand-edited tree is never silently wiped).`,
        ]
      : []
  })
}
