import type { ReplacementRecord } from './overlay.js'
import { compareCodeUnits } from './paths.js'

/** Generated, types only (no runtime): gives `pv-original:<specifier>` the exact type of PV's own
 * file. It lives under the composed `src/`, so it is rewritten on every compose and never hand
 * edited. Without replacements there is nothing to declare and no file. */
export const PV_ORIGINAL_TYPES_PATH = 'src/lib/_cm/_pv-original.d.ts'

const HEADER =
  '// Generated by @project-vault/composition-kit (pv-compose). DO NOT EDIT.\n' +
  "// Types only: each `pv-original:` import has the exact type of PV's original file.\n" +
  '/// <reference types="@project-vault/composition-kit/pv-original" />\n'
const LIB = 'src/lib/'

/** A module has a default export when it says so; `.svelte` components always do. */
function hasDefault(hostPath: string, hostText: string): boolean {
  return hostPath.endsWith('.svelte') || /\bexport\s+default\b|\bas\s+default\b/.test(hostText)
}

function declaration(specifier: string, withDefault: boolean): string {
  const lines = [`  export * from '${specifier}'`]
  if (withDefault) lines.push(`  export { default } from '${specifier}'`)
  return `declare module 'pv-original:${specifier}' {\n${lines.join('\n')}\n}\n`
}

/** One declaration per spelling CM can use: the manifest key, and the canonical `$lib/<file>`. */
export function pvOriginalDeclarations(
  replacements: readonly ReplacementRecord[],
  readHost: (hostPath: string) => string
): string | null {
  const specifiers = new Map<string, boolean>()
  for (const record of replacements) {
    const withDefault = hasDefault(record.hostPath, readHost(record.hostPath))
    specifiers.set(record.target, withDefault)
    if (record.hostPath.startsWith(LIB)) {
      specifiers.set(`$lib/${record.hostPath.slice(LIB.length)}`, withDefault)
    }
  }
  if (specifiers.size === 0) return null
  const body = [...specifiers]
    .sort(([a], [b]) => compareCodeUnits(a, b))
    .map(([specifier, withDefault]) => declaration(specifier, withDefault))
  return `${HEADER}\n${body.join('\n')}`
}
