import { baseRules, secretsRules, svelteRules, webEnforcement } from '@project-vault/eslint-config'

export default [
  {
    ignores: [
      '.svelte-kit/**',
      'build/**',
      'dist/**',
      'node_modules/**',
      'coverage/**',
      '**/.stryker-tmp/**',
      // Story 15.1: auto-generated by @inlang/paraglide-js's Vite plugin at build/dev time — not
      // hand-written app source (see vite.config.ts's paraglideVitePlugin).
      'src/lib/paraglide/**',
    ],
  },
  ...baseRules,
  ...secretsRules,
  ...svelteRules,
  ...webEnforcement,
  {
    files: ['src/**/*.test.ts'],
    rules: {
      'no-secrets/no-secrets': 'off',
      'sonarjs/no-duplicate-string': 'off',
      'security/detect-non-literal-fs-filename': 'off',
    },
  },
]
