import { baseRules, secretsRules, svelteRules, webEnforcement } from '@project-vault/eslint-config'

// Story 68.7 Q1 (option A): the nav renderers render hrefs that come from nav data (PV's and, in a
// composed app, CM's), typed `ResolvedPathname` because every link item's href is produced by
// `resolve()` where the item is defined. Type-aware parsing lets `svelte/no-navigation-without-resolve`
// accept exactly that type (a tightening: these files also get the type-aware rules). Scoped to the
// renderers, which keeps `eslint .` within 1.2x of its untyped time (10.2 s -> 11.6 s measured);
// `src/lib/navigation/nav-lint-scope.test.ts` keeps every registered renderer in this list.
export const NAV_RENDERER_FILES = [
  'src/lib/navigation/**/*.svelte',
  'src/lib/components/shell/AppShell.svelte',
  'src/lib/components/shell/Footer.svelte',
  'src/lib/components/shell/NotificationsLink.svelte',
  'src/lib/components/shell/PrimaryNav.svelte',
  'src/lib/components/shell/ProjectNav.svelte',
  'src/lib/components/shell/ShellAccount.svelte',
  'src/lib/components/shell/ShellBrand.svelte',
  'src/lib/components/public/RootErrorContent.svelte',
]

export default [
  {
    ignores: [
      '.svelte-kit/**',
      'build/**',
      'dist/**',
      'node_modules/**',
      'coverage/**',
      '**/.stryker-tmp/**',
      // Story 15.1: auto-generated by @inlang/paraglide-js's Vite plugin at build/dev time — not
      // hand-written app source (see vite.config.ts's paraglideVitePlugin).
      'src/lib/paraglide/**',
      // Story 66.1: Playwright's generated report/traces from a local `make e2e` run.
      'e2e/test-results/**',
    ],
  },
  ...baseRules,
  ...secretsRules,
  ...svelteRules,
  ...webEnforcement,
  {
    files: NAV_RENDERER_FILES,
    languageOptions: {
      parserOptions: { projectService: true, tsconfigRootDir: import.meta.dirname },
    },
  },
  {
    files: ['src/**/*.test.ts'],
    rules: {
      'no-secrets/no-secrets': 'off',
      'sonarjs/no-duplicate-string': 'off',
      'security/detect-non-literal-fs-filename': 'off',
    },
  },
]
