sonar.organization=nestormata
sonar.projectKey=nestormata_project-vault
sonar.projectName=project-vault

sonar.sources=apps,packages
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/.svelte-kit/**,**/*.d.ts

sonar.tests=apps,packages
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
sonar.test.exclusions=**/node_modules/**,**/dist/**,**/build/**

sonar.javascript.lcov.reportPaths=apps/api/coverage/lcov.info,apps/web/coverage/lcov.info,packages/agent/coverage/lcov.info,packages/crypto/coverage/lcov.info,packages/db/coverage/lcov.info,packages/shared/coverage/lcov.info,packages/vault-action/coverage/lcov.info
