// Story 68.5 Task 2 / AC-11: the composer writes per-replacement `declare module 'pv-original:...'`
// declarations (types only) so a `pv-original:` import has PV's original file's exact type.
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { compose } from '../src/compose.js'
import { PV_ORIGINAL_TYPES_PATH } from '../src/pv-original-types.js'
import {
  makeWorld,
  manifest,
  sha,
  shaOf,
  useWorlds,
  writeAll,
  type World,
} from './compose-test-helpers.js'

useWorlds()

const SEARCH = 'src/lib/components/shell/GlobalSearch.svelte'
const PACK = {
  'r/GlobalSearch.svelte': '<input class="cm" />\n',
  'r/auth.ts': 'export const requireUser = () => false\n',
  'r/fmt.ts': 'export const fmt = () => ""\n',
}

function replace(world: World, entries: Record<string, [string, string]>) {
  return manifest({
    replacements: Object.fromEntries(
      Object.entries(entries).map(([target, [withPath, hostRel]]) => [
        target,
        { with: withPath, hostSha256: sha(world, hostRel) },
      ])
    ),
  })
}

function run(world: World, pack: unknown) {
  return compose({ appRoot: world.app, packRoot: world.pack, hostDir: world.host, manifest: pack })
}

function types(world: World): string {
  return readFileSync(join(world.app, PV_ORIGINAL_TYPES_PATH), 'utf8')
}

describe('generated pv-original declarations', () => {
  it('declares each replaced file by its manifest key, with exact re-exports', async () => {
    const world = makeWorld({ packFiles: PACK })
    const pack = replace(world, {
      '$lib/components/shell/GlobalSearch.svelte': ['./r/GlobalSearch.svelte', SEARCH],
      '$lib/server/auth.ts': ['./r/auth.ts', 'src/lib/server/auth.ts'],
    })
    expect((await run(world, pack)).messages).toEqual([])
    const text = types(world)
    expect(text).toContain(
      "declare module 'pv-original:$lib/components/shell/GlobalSearch.svelte' {\n  export * from '$lib/components/shell/GlobalSearch.svelte'\n  export { default } from '$lib/components/shell/GlobalSearch.svelte'\n}"
    )
    // A .ts module without a default export gets only `export *`.
    expect(text).toContain(
      "declare module 'pv-original:$lib/server/auth.ts' {\n  export * from '$lib/server/auth.ts'\n}"
    )
    expect(text).toContain('Generated by @project-vault/composition-kit')
    expect(text).toContain('/// <reference types="@project-vault/composition-kit/pv-original" />')
  })

  it('also declares the canonical $lib spelling of an extension-less key', async () => {
    const world = makeWorld({ packFiles: PACK })
    const pack = replace(world, {
      '$lib/components/shell/GlobalSearch': ['./r/GlobalSearch.svelte', SEARCH],
    })
    await run(world, pack)
    const text = types(world)
    expect(text).toContain("declare module 'pv-original:$lib/components/shell/GlobalSearch' {")
    expect(text).toContain(
      "declare module 'pv-original:$lib/components/shell/GlobalSearch.svelte' {"
    )
  })

  it('re-exports a default when the PV module has one', async () => {
    const world = makeWorld({
      packFiles: PACK,
      hostFiles: { 'src/lib/fmt.ts': 'export default function fmt() {}\n' },
    })
    const pack = manifest({
      replacements: {
        '$lib/fmt.ts': {
          with: './r/fmt.ts',
          hostSha256: shaOf('export default function fmt() {}\n'),
        },
      },
    })
    await run(world, pack)
    expect(types(world)).toContain("export { default } from '$lib/fmt.ts'")
  })

  it('writes nothing when there are no replacements, and is deterministic otherwise', async () => {
    const empty = makeWorld()
    await run(empty, manifest())
    expect(existsSync(join(empty.app, PV_ORIGINAL_TYPES_PATH))).toBe(false)

    const world = makeWorld({ packFiles: PACK })
    const pack = replace(world, { '$lib/util.ts': ['./r/fmt.ts', 'src/lib/util.ts'] })
    await run(world, pack)
    const first = types(world)
    writeAll(world.pack, { 'r/fmt.ts': 'export const fmt = () => "v2"\n' })
    await run(world, pack)
    expect(types(world)).toBe(first)
  })
})
