#!/usr/bin/env tsx
/**
 * Story 68.10: the runner of the mock UI pack mechanism e2e (`make mock-ui-pack-e2e`). Host-side,
 * exactly like `make composition-kit-integration`: the `make ci` container has no Docker CLI.
 *
 * Named stages, each its own step so a red run says which one failed:
 *   Pack               pack web-host and the kit, resolve extension-api (scripts/lib/web-host)
 *   Compose            pv-compose, pv-compose --check, pv-verify, svelte-check, build and boot in the
 *                      isolated consumer (run.sh variant compose-mock-pack), exporting the composed
 *                      app as a Docker build context
 *   Build composed image + Boot stack
 *                      scripts/e2e-stack.sh with E2E_STACK_FLAVOR=mock-ui-pack (real API, real
 *                      database, the composed web image); ports and project name are per run
 *   Mechanism e2e      Playwright (apps/web/playwright.mechanism.config.ts), one file per capability
 *   Teardown           `down -v --remove-orphans` by project name, always (unless E2E_STACK_KEEP=1)
 *
 *   tsx scripts/mock-ui-pack-e2e.ts [<spec path relative to apps/web>]
 *
 * Secrets: the 12 throwaway secrets are generated by e2e-stack.sh in ITS process only. This runner
 * never reads, prints or passes one, and never prints a resolved compose configuration.
 */
import { spawnSync } from 'node:child_process'
import { cpSync, mkdtempSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { REPO_ROOT } from './pack-web-host.js'
import { resolveBin, resolveTrustedExecutable } from './lib/trusted-executable.js'
import {
  consumerFixtureEnv,
  packConsumerTarballs,
  type ConsumerTarballs,
} from './lib/web-host/consumer-tarballs.js'

const FIXTURES = 'fixtures'
const STACK_SCRIPT = join(REPO_ROOT, 'scripts', 'e2e-stack.sh')
const FIXTURE_SCRIPT = join(REPO_ROOT, 'scripts', 'web-host-consumer-fixture', 'run.sh')
const PACK_NAME = 'mock-ui-pack'
const PACK_DIR = join(REPO_ROOT, FIXTURES, PACK_NAME)
const WEB_DIR = join(REPO_ROOT, 'apps', 'web')
const COMPOSE_TIMEOUT_MS = 30 * 60_000
const FLAVOR = 'mock-ui-pack'

function stage(name: string): void {
  process.stdout.write(`\n=== ${name} ===\n`)
}

function bash(args: string[], env: NodeJS.ProcessEnv, options: { inherit: boolean }) {
  return spawnSync(resolveTrustedExecutable('bash'), args, {
    cwd: REPO_ROOT,
    env,
    encoding: 'utf8',
    stdio: options.inherit ? 'inherit' : ['ignore', 'pipe', 'inherit'],
    timeout: COMPOSE_TIMEOUT_MS,
  })
}

/** The `NAME=value` lines `e2e-stack.sh plan` prints (ports, origin, project name; no secrets). */
function parsePlan(output: string): Record<string, string> {
  return Object.fromEntries(
    output
      .split('\n')
      .filter((line) => /^[A-Z_]+=\S+$/.test(line))
      .map((line) => [line.slice(0, line.indexOf('=')), line.slice(line.indexOf('=') + 1)])
  )
}

function compose(workDir: string, tarballs: ConsumerTarballs, contextDir: string): void {
  const env = consumerFixtureEnv(process.env, workDir, tarballs, {
    fixturesDir: join(workDir, FIXTURES),
  })
  const run = bash(
    [FIXTURE_SCRIPT, tarballs.webHostTarball, 'compose-mock-pack'],
    {
      ...env,
      MOCK_UI_PACK_CONTEXT_OUT: contextDir,
    },
    { inherit: true }
  )
  if (run.status !== 0) throw new Error(`Compose stage failed (exit ${String(run.status)})`)
  const docker = join(PACK_DIR, 'docker')
  cpSync(join(docker, 'web.Dockerfile'), join(contextDir, 'web.Dockerfile'))
  cpSync(join(docker, '.dockerignore'), join(contextDir, '.dockerignore'))
}

function planStack(contextDir: string): NodeJS.ProcessEnv {
  const base = { ...process.env, E2E_STACK_FLAVOR: FLAVOR, MOCK_UI_PACK_WEB_CONTEXT: contextDir }
  const plan = bash([STACK_SCRIPT, 'plan'], base, { inherit: false })
  if (plan.status !== 0) throw new Error('could not plan the stack (ports, project name)')
  return { ...base, ...parsePlan(plan.stdout) }
}

function runPlaywright(stack: NodeJS.ProcessEnv, spec: string | undefined): number {
  const playwright = resolveBin('@playwright/test', 'playwright', WEB_DIR)
  const dbPort = stack['DB_HOST_PORT'] ?? ''
  const args = [playwright, 'test', '-c', 'playwright.mechanism.config.ts', ...(spec ? [spec] : [])]
  const run = spawnSync(process.execPath, args, {
    cwd: WEB_DIR,
    stdio: 'inherit',
    env: {
      ...stack,
      E2E_BASE_URL: stack['PUBLIC_WEB_ORIGIN'],
      E2E_API_BASE_URL: `http://localhost:${stack['API_HOST_PORT'] ?? ''}`,
      E2E_SUPERUSER_DATABASE_URL: `postgresql://postgres:password@localhost:${dbPort}/project_vault`,
    },
  })
  return run.status ?? 1
}

async function main(): Promise<number> {
  const spec = process.argv[2]
  const workDir = mkdtempSync(join(tmpdir(), 'mock-ui-pack-e2e-'))
  const contextDir = join(workDir, 'context')
  let stack: NodeJS.ProcessEnv | undefined
  try {
    stage('Pack')
    const tarballs = await packConsumerTarballs(workDir)
    cpSync(join(PACK_DIR, 'ui-pack'), join(workDir, FIXTURES, PACK_NAME), {
      recursive: true,
    })
    stage('Compose')
    compose(workDir, tarballs, contextDir)
    stage('Build composed image and boot stack')
    stack = planStack(contextDir)
    const started = bash([STACK_SCRIPT, 'start'], stack, { inherit: true })
    if (started.status !== 0) throw new Error('Boot stack failed')
    stage('Mechanism e2e')
    return runPlaywright(stack, spec)
  } catch (error) {
    process.stderr.write(`mock-ui-pack-e2e: ${(error as Error).message}\n`)
    return 1
  } finally {
    stage('Teardown')
    if (stack !== undefined && process.env['E2E_STACK_KEEP'] !== '1') {
      bash([STACK_SCRIPT, 'down'], stack, { inherit: true })
    } else if (stack !== undefined) {
      const kept = ['COMPOSE_PROJECT_NAME', 'WEB_HOST_PORT', 'API_HOST_PORT', 'DB_HOST_PORT']
      process.stdout.write(
        `kept stack (E2E_STACK_KEEP=1): ${kept.map((name) => `${name}=${stack?.[name] ?? ''}`).join(' ')}\n`
      )
    }
    rmSync(workDir, { recursive: true, force: true })
  }
}

void main().then((code) => {
  process.exitCode = code
})
